name: GoXLR

options:
  xcodeVersion: 14.2
  deploymentTarget:
    macOS: 13.0
  developmentLanguage: en
  groupSortPosition: top
  generateEmptyDirectories: true
  groupOrdering:
    - order: [GoXLR]
    - pattern: 'GoXLR'
      order: [View, Extensions, Resources]
    - pattern: 'View'
      order: [Root]
    - pattern: 'Resources'
      order: [App, Interface, Utility]
    - pattern: 'App'
      order: [Root, Info, Settings]
    - pattern: 'Interface'
      order: [Assets, Typography]
    - pattern: 'Utility'
      order: [Daemon, Initializer]

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

packages:
  CoreKit:
    url: https://github.com/multixlr/CoreKit.git
    branch: main

targets:
  GoXLR:
    type: application
    platform: macOS
    sources:
      - GoXLR
      - path: GoXLR/Resources/Utility/Daemon/goxlr-daemon
        buildPhase: resources
    dependencies:
      - package: CoreKit
    entitlements:
      path: GoXLR/Resources/GoXLR.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.cs.allow-unsigned-executable-memory: true
        com.apple.security.files.user-selected.read-only: true
    settings:
      base:
        PRODUCT_NAME: GoXLR
        PRODUCT_MODULE_NAME: GoXLR
        PRODUCT_BUNDLE_IDENTIFIER: 'com.multixlr.goxlr'
        DEVELOPMENT_TEAM: KVH9XSM27S
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: GoXLR/Resources/App/Info/Info.plist
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          CODE_SIGN_ENTITLEMENTS: GoXLR/Resources/GoXLR.entitlements
        Release:
          CODE_SIGN_ENTITLEMENTS: GoXLR/Resources/GoXLR.entitlements
      
